name: Build and Deploy Image PUMA_Reporting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out code di repository
        uses: actions/checkout@v5
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_PAT }}
          

      - name: Log in ke GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build dan Push Image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/puma_reporting:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Login ke GHCR di server
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Update docker compose dan .env
        run: |
          # Buat folder jika tidak eksis
          mkdir -p ~/reporting/puma
          cd ~/reporting/puma

          # Unduh docker-compose terbaru
          curl -fsSLO https://raw.githubusercontent.com/johanesPao/puma_reporting/main/docker-compose.yml

          # Write .env into folder
          cat > .env <<EOF
          ENV_HOST=${{ secrets.ENV_HOST }}
          ENV_PROJECT_ID=${{ secrets.ENV_PROJECT_ID }}
          ENV_CLIENT_ID=${{ secrets.ENV_CLIENT_ID }}
          ENV_CLIENT_SECRET=${{ secrets.ENV_CLIENT_SECRET }}
          EOF

          chmod 600 .env


