name: Build and Deploy Image PUMA_Reporting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dan-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out code di repository
        uses: actions/checkout@v5

      - name: Log in ke GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build dan Push Image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/puma_reporting:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
